# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/input_data_fifo/input_data_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==input_data_fifo || ORIG_REF_NAME==input_data_fifo} -quiet] -quiet
