# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/johnh/Desktop/DICE-Project/mig_7series_0_ex/mig_7series_0_ex.srcs/sources_1/ip/ila_ddr2_axi/ila_ddr2_axi.xci
# IP: The module: 'ila_ddr2_axi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/DICE-Project/mig_7series_0_ex/mig_7series_0_ex.gen/sources_1/ip/ila_ddr2_axi/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ddr2_axi'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnh/Desktop/DICE-Project/mig_7series_0_ex/mig_7series_0_ex.gen/sources_1/ip/ila_ddr2_axi/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ddr2_axi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnh/Desktop/DICE-Project/mig_7series_0_ex/mig_7series_0_ex.gen/sources_1/ip/ila_ddr2_axi/ila_ddr2_axi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ddr2_axi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/johnh/Desktop/DICE-Project/mig_7series_0_ex/mig_7series_0_ex.srcs/sources_1/ip/ila_ddr2_axi/ila_ddr2_axi.xci
# IP: The module: 'ila_ddr2_axi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/DICE-Project/mig_7series_0_ex/mig_7series_0_ex.gen/sources_1/ip/ila_ddr2_axi/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ddr2_axi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnh/Desktop/DICE-Project/mig_7series_0_ex/mig_7series_0_ex.gen/sources_1/ip/ila_ddr2_axi/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ddr2_axi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/johnh/Desktop/DICE-Project/mig_7series_0_ex/mig_7series_0_ex.gen/sources_1/ip/ila_ddr2_axi/ila_ddr2_axi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ddr2_axi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
