# For Spartan-6
# 32-bit Multi-Channel FIFO Bus Master Mode
#
#
# Pin Assignment 
#

#
# FIFO INTF 
#
NET CLK LOC R10 IOSTANDARDLVCMOS25 SCHMITT_TRIGGER
NET RXF_N LOC N6 IOSTANDARDLVCMOS25 #for M600 mode, ACK_N
NET TXE_N LOC P7 IOSTANDARDLVCMOS25
NET SIWU_N LOC T7 IOSTANDARDLVCMOS25 SLEWFAST
NET WR_N LOC R7 IOSTANDARDLVCMOS25 SLEWFAST 
NET RD_N LOC P8 IOSTANDARDLVCMOS25 SLEWFAST
NET OE_N LOC N7 IOSTANDARDLVCMOS25 SLEWFAST
NET BE[0] LOC V4 IOSTANDARDLVCMOS25 SLEWFAST
NET BE[1] LOC T4 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[0] LOC V15 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[1] LOC N9 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[2] LOC U15 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[3] LOC M10 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[4] LOC V12 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[5] LOC V6 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[6] LOC T12 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[7] LOC T6 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[8] LOC V11 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[9] LOC N8 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[10] LOC U11 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[11] LOC M8 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[12] LOC V8 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[13] LOC N11 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[14] LOC U8 IOSTANDARDLVCMOS25 SLEWFAST
NET DATA[15] LOC M11 IOSTANDARDLVCMOS25 SLEWFAST
#
NET R_OOB LOC B2 IOSTANDARDLVCMOS25 SLEWFAST
NET W_OOB LOC A2 IOSTANDARDLVCMOS25 SLEWFAST
#
#
# SYSTEM INTF 
#
NET SRST_N LOC C8 
NET HRST_N LOC P4 

NET STRER[3] LOC A4 
NET STRER[2] LOC C4 
NET STRER[1] LOC C14 
NET STRER[0] LOC E13 

NET MLTCN LOC D14
NET STREN LOC E12
NET ERDIS LOC F12

#
# CLOCK 
#
NET CLK TNM_NET CLK 
TIMESPEC TS_CLK PERIOD CLK 10 ns HIGH 50.00% INPUT_JITTER 800 ps PRIORITY 1 

#
# IO constraints 
#
NET DATA<*> TNM M_FIFO_IO
NET BE<*> TNM M_FIFO_IO
NET RXF_N TNM M_FIFO_I
NET TXE_N TNM M_FIFO_I1
NET WR_N TNM M_FIFO_O
NET RD_N TNM M_FIFO_O
NET OE_N TNM M_FIFO_O
#
NET SIWU_N TNM LED_O
NET STRER<*> TNM LED_O
#
INST i1_fsm/odata* IOBTRUE
INST i1_fsm/obe* IOBTRUE
INST i1_fsm/wr_n IOBTRUE
INST i1_fsm/rd_n IOBTRUE
INST i1_fsm/oe_n IOBTRUE
INST i1_fsm/irxf_n* IOBTRUE

#
# Exceptions 
#

NET i1_fsm/be_oe_n TPTHRU OUT_EN
NET i1_fsm/dt_oe_n TPTHRU OUT_EN

NET HRST_N TNM IN_TIG
NET SRST_N TNM IN_TIG
NET R_OOB TNM IN_TIG
NET W_OOB TNM IN_TIG
NET MLTCN TNM IN_TIG
NET STREN TNM IN_TIG
NET ERDIS TNM IN_TIG
#
TIMESPEC TS_TIG FROM IN_TIG TO FFS TIG 
TIMESPEC TS_TIG FROM FFS TO LED_O TIG
TIMESPEC TS_TIG FROM M_FIFO_I1 TO FFS TIG 
TIMESPEC TS_TIG FROM CLK THRU OUT_EN TO M_FIFO_IO TIG 
# IO timing 
TIMEGRP M_FIFO_IO OFFSET IN 6 ns VALID 6.5 ns BEFORE CLK RISING
TIMEGRP M_FIFO_I OFFSET IN 6 ns VALID 6.5 ns BEFORE CLK RISING

TIMEGRP M_FIFO_IO OFFSET OUT 9 ns VALID 5.8 ns AFTER CLK RISING
TIMEGRP M_FIFO_O OFFSET OUT 9 ns VALID 5.8 ns AFTER CLK RISING
# End of generated constraints