# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/johnh/Desktop/DICE/Hardware/FPGA/Laplacian Core/laplacian_core/laplacian_core.srcs/sources_1/ip/dsp_msub/dsp_msub.xci
# IP: The module: 'dsp_msub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/DICE/Hardware/FPGA/Laplacian Core/laplacian_core/laplacian_core.gen/sources_1/ip/dsp_msub/dsp_msub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_msub'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/johnh/Desktop/DICE/Hardware/FPGA/Laplacian Core/laplacian_core/laplacian_core.srcs/sources_1/ip/dsp_msub/dsp_msub.xci
# IP: The module: 'dsp_msub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/DICE/Hardware/FPGA/Laplacian Core/laplacian_core/laplacian_core.gen/sources_1/ip/dsp_msub/dsp_msub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_msub'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
