# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/micha/OneDrive/Desktop/DICE/Hardware/FPGA/FT600 Loopback/Project/FT600_Loopback.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
# IP: The module: 'blk_mem_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/micha/OneDrive/Desktop/DICE/Hardware/FPGA/FT600 Loopback/Project/FT600_Loopback.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/micha/OneDrive/Desktop/DICE/Hardware/FPGA/FT600 Loopback/Project/FT600_Loopback.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
# IP: The module: 'blk_mem_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/micha/OneDrive/Desktop/DICE/Hardware/FPGA/FT600 Loopback/Project/FT600_Loopback.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
