##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Wed Apr  3 18:36:35 2024

##  Generated by MIG Version 4.2
##  
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A200T-FBG484
##                    Speedgrade:        -3
##                    Design Entry:      VERILOG
##                    Frequency:         400 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR2_SDRAM->Components->MT47H128M16XX-25E
## Data Width: 16
## Time Period: 2500
## Data Mask: 1
##################################################################################################
############## NET - IOSTANDARD ##################


# PadFunction: IO_L10N_T1_16 
set_property IOSTANDARD LVCMOS25 [get_ports {init_calib_complete}]
set_property PACKAGE_PIN A14 [get_ports {init_calib_complete}]

# PadFunction: IO_L9P_T1_DQS_16 
set_property IOSTANDARD LVCMOS25 [get_ports {tg_compare_error}]
set_property PACKAGE_PIN A15 [get_ports {tg_compare_error}]


set_property INTERNAL_VREF  0.900 [get_iobanks 34]
set_property INTERNAL_VREF  0.900 [get_iobanks 35]