# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/johnh/Desktop/DICE/Hardware/FPGA/comp_tst/usb_compressor_test/usb_compressor_test.srcs/sources_1/ip/input_sync_memory/input_sync_memory.xci
# IP: The module: 'input_sync_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/DICE/Hardware/FPGA/comp_tst/usb_compressor_test/usb_compressor_test.gen/sources_1/ip/input_sync_memory/input_sync_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_sync_memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/johnh/Desktop/DICE/Hardware/FPGA/comp_tst/usb_compressor_test/usb_compressor_test.srcs/sources_1/ip/input_sync_memory/input_sync_memory.xci
# IP: The module: 'input_sync_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/DICE/Hardware/FPGA/comp_tst/usb_compressor_test/usb_compressor_test.gen/sources_1/ip/input_sync_memory/input_sync_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_sync_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
