# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/dsp_msub/dsp_msub.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_msub || ORIG_REF_NAME==dsp_msub} -quiet] -quiet

# IP: ip/dsp_acum/dsp_acum.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_acum || ORIG_REF_NAME==dsp_acum} -quiet] -quiet

# IP: ip/dsp_mac/dsp_mac.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_mac || ORIG_REF_NAME==dsp_mac} -quiet] -quiet

# IP: ip/dsp_macro_add_22b/dsp_macro_add_22b.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_add_22b || ORIG_REF_NAME==dsp_macro_add_22b} -quiet] -quiet

# IP: ip/dsp_macro_simd/dsp_macro_simd.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_simd || ORIG_REF_NAME==dsp_macro_simd} -quiet] -quiet
