# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/dsp_macro_add_22b/dsp_macro_add_22b.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_add_22b || ORIG_REF_NAME==dsp_macro_add_22b} -quiet] -quiet
