# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.runs/synth_1/mipi_csi_top_v2.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_param chipscope.maxJobs 4
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_param synth.incrementalSynthesisCache C:/Users/johnh/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-23100-DESKTOP-U9NB2CD/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku3p-ffva676-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.cache/wt [current_project]
set_property parent.project_path C:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/hdmi controller/video_define.v}
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/hdmi controller/i2c_master/timescale.v}
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/hdmi controller/i2c_master/i2c_master_defines.v}
}
set_property file_type "Verilog Header" [get_files {{C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/hdmi controller/video_define.v}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/hdmi controller/i2c_master/timescale.v}}]
set_property file_type "Verilog Header" [get_files {{C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/hdmi controller/i2c_master/i2c_master_defines.v}}]
read_verilog -library xil_defaultlib {
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/video controller/color_bar.v}
  C:/Users/johnh/Desktop/camera_test_v2/imports/verilog/src/debayer_filter_xilinx.v
  C:/Users/johnh/Desktop/camera_test_v2/imports/verilog/src/frame_detector.v
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/hdmi controller/i2c_master/i2c_config.v}
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/hdmi controller/i2c_master/i2c_master_bit_ctrl.v}
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/hdmi controller/i2c_master/i2c_master_byte_ctrl.v}
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/hdmi controller/i2c_master/i2c_master_top.v}
  C:/Users/johnh/Desktop/camera_test_v2/imports/verilog/src/lsync_reset_generator.v
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/hdmi controller/lut_hdmi_out.v}
  C:/Users/johnh/Desktop/camera_test_v2/imports/verilog/src/mipi_csi_rx_byte_aligner.v
  C:/Users/johnh/Desktop/camera_test_v2/imports/verilog/src/mipi_csi_rx_lane_aligner.v
  C:/Users/johnh/Desktop/camera_test_v2/imports/verilog/src/mipi_csi_rx_packet_decoder_8b4lane.v
  C:/Users/johnh/Desktop/camera_test_v2/imports/verilog/src/mipi_csi_rx_raw_depacker_8b4lane.v
  C:/Users/johnh/Desktop/camera_test_v2/imports/verilog/src/output_reformatter_rgb24.v
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/hdmi controller/reset_power_on.v}
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/video controller/video_timing_ctrl.vhd}
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/video controller/video_mux.vhd}
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/hdmi controller/hdmi_ctrl_top.vhd}
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/mipi controller/mipi_parameters.vhd}
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/mipi controller/mipi_dphy.vhd}
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/mipi controller/mipi_csi_rx_controller.vhd}
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/mipi controller/pixel_processor.vhd}
  {C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/mipi controller/mipi_csi_top_v2.vhd}
}
read_vhdl -library xil_defaultlib {{C:/Users/johnh/Desktop/camera_test_v2/imports/vhdl/src/mipi controller/register_stage.vhd}}
read_ip -quiet C:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet C:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet C:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.gen/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet C:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.srcs/sources_1/ip/vio_0/vio_0.xci
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.gen/sources_1/ip/vio_0/vio_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.gen/sources_1/ip/vio_0/vio_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.srcs/constrs_2/new/mipi_csi_top_v2.xdc
set_property used_in_implementation false [get_files C:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.srcs/constrs_2/new/mipi_csi_top_v2.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Users/johnh/Desktop/camera_test_v2/camera_test_v2.srcs/utils_1/imports/synth_1/mipi_csi_top_v2.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mipi_csi_top_v2 -part xcku3p-ffva676-2-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mipi_csi_top_v2.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mipi_csi_top_v2_utilization_synth.rpt -pb mipi_csi_top_v2_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
