# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/johnh/Desktop/DICE/Hardware/FPGA/Image Stats/image_statistics/image_statistics.srcs/sources_1/ip/dsp_macro_simd/dsp_macro_simd.xci
# IP: The module: 'dsp_macro_simd' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/DICE/Hardware/FPGA/Image Stats/image_statistics/image_statistics.gen/sources_1/ip/dsp_macro_simd/dsp_macro_simd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_macro_simd'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/johnh/Desktop/DICE/Hardware/FPGA/Image Stats/image_statistics/image_statistics.srcs/sources_1/ip/dsp_macro_simd/dsp_macro_simd.xci
# IP: The module: 'dsp_macro_simd' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/johnh/Desktop/DICE/Hardware/FPGA/Image Stats/image_statistics/image_statistics.gen/sources_1/ip/dsp_macro_simd/dsp_macro_simd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_macro_simd'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
