set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[3]}]
set_property PACKAGE_PIN B21 [get_ports {dram_dq[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[0]}]
set_property PACKAGE_PIN C21 [get_ports {dram_dq[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[1]}]
set_property PACKAGE_PIN A20 [get_ports {dram_dq[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[2]}]
set_property PACKAGE_PIN B25 [get_ports {dram_dq[3]}]
set_property PACKAGE_PIN A19 [get_ports {dram_dq[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[4]}]
set_property PACKAGE_PIN B24 [get_ports {dram_dq[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[5]}]
set_property PACKAGE_PIN D23 [get_ports {dram_dq[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[6]}]
set_property PACKAGE_PIN D21 [get_ports {dram_dq[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[7]}]
set_property PACKAGE_PIN D24 [get_ports {dram_dq[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[8]}]
set_property PACKAGE_PIN B22 [get_ports {dram_dq[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[9]}]
set_property PACKAGE_PIN B26 [get_ports {dram_dq[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[10]}]
set_property PACKAGE_PIN C22 [get_ports {dram_dq[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[11]}]
set_property PACKAGE_PIN D25 [get_ports {dram_dq[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[12]}]
set_property PACKAGE_PIN C23 [get_ports {dram_dq[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[13]}]
set_property PACKAGE_PIN D26 [get_ports {dram_dq[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[14]}]
set_property PACKAGE_PIN C24 [get_ports {dram_dq[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_dq[15]}]
set_property PACKAGE_PIN B20 [get_ports {dram_rwds[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_rwds[0]}]
set_property PACKAGE_PIN C26 [get_ports {dram_rwds[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {dram_rwds[1]}]
set_property PACKAGE_PIN G11 [get_ports mmcm_locked]
set_property IOSTANDARD LVCMOS18 [get_ports mmcm_locked]

set_property PACKAGE_PIN D19 [get_ports sys_clk_p]
set_property IOSTANDARD LVDS [get_ports sys_clk_p]
set_property PACKAGE_PIN A25 [get_ports dram_clk_n]

set_property PACKAGE_PIN A23 [get_ports dram_cs]
set_property IOSTANDARD LVCMOS18 [get_ports dram_cs]

set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports dram_clk_p]

set_property PACKAGE_PIN E22 [get_ports reset_in]
set_property IOSTANDARD LVCMOS18 [get_ports reset_in]
set_property PACKAGE_PIN J10 [get_ports reset_out]
set_property IOSTANDARD LVCMOS18 [get_ports reset_out]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_200m]
