
# Input Clock and Reset
set_property PACKAGE_PIN E22 [get_ports reset_i]
set_property PACKAGE_PIN D19 [get_ports sys_clk_p_i]

set_property IOSTANDARD LVCMOS18 [get_ports reset_i]
set_property IOSTANDARD LVDS [get_ports sys_clk_p_i]

#create_clock -period 5.000 -name sys_clk_p -waveform {0.000 2.500} -add [get_ports sys_clk_p_i]


# MIPI D-PHY Pins
set_property PACKAGE_PIN J10 [get_ports phy_ready_o]
set_property PACKAGE_PIN G11 [get_ports mmcm_locked_o]
set_property PACKAGE_PIN AA19 [get_ports {dphy_clk_i[1]}]
set_property PACKAGE_PIN AB21 [get_ports {dphy_data_p_i[3]}]
set_property PACKAGE_PIN AD20 [get_ports {dphy_data_p_i[2]}]
set_property PACKAGE_PIN AC19 [get_ports {dphy_data_p_i[1]}]

# MIPI D-PHY IO Standards
set_property IOSTANDARD LVCMOS18 [get_ports mmcm_locked_o]
set_property IOSTANDARD LVCMOS18 [get_ports phy_ready_o]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_clk_i[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_clk_i[0]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_data_p_i[3]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_data_p_i[2]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_data_p_i[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_data_p_i[0]}]

#create_clock -period 10.000 -name dphy_byte_clk -waveform {0.000 5.000} [get_nets {dphy_byte_clk_x}]
#create_clock -period 2.500 -name csi -waveform {0.000 1.250} [get_ports {dphy_clk_i[1]}]
#create_clock -period 2.500 -name csi2 -waveform {1.250 2.500} [get_ports {dphy_clk_i[0]}]
#set_input_delay -clock [get_clocks csi] -add_delay 1.000 [get_ports {{dphy_data_p_i[0]} {dphy_data_n_i[0]} {dphy_data_p_i[1]} {dphy_data_n_i[1]} {dphy_data_p_i[2]} {dphy_data_n_i[2]} {dphy_data_p_i[3]} {dphy_data_n_i[3]}}]
#set_input_delay -clock [get_clocks csi] -clock_fall -add_delay 1.000 [get_ports {{dphy_data_p_i[0]} {dphy_data_n_i[0]} {dphy_data_p_i[1]} {dphy_data_n_i[1]} {dphy_data_p_i[2]} {dphy_data_n_i[2]} {dphy_data_p_i[3]} {dphy_data_n_i[3]}}]


# HDMI IO Pins
set_property PACKAGE_PIN AA15 [get_ports hdmi_de_o]
set_property PACKAGE_PIN AB15 [get_ports hdmi_hs_o]
set_property PACKAGE_PIN AF15 [get_ports hdmi_i2c_scl_io]
set_property PACKAGE_PIN AE16 [get_ports hdmi_i2c_sda_io]
set_property PACKAGE_PIN AF12 [get_ports hdmi_nrst_o]
set_property PACKAGE_PIN W15 [get_ports hdmi_pixel_clk_o]
set_property PACKAGE_PIN Y15 [get_ports hdmi_vs_o]
set_property PACKAGE_PIN G14 [get_ports video_src_sel]

set_property PACKAGE_PIN W20 [get_ports {dphy_data_p_i[0]}]
set_property PACKAGE_PIN AD9 [get_ports {hdmi_data_o[23]}]
set_property PACKAGE_PIN AC9 [get_ports {hdmi_data_o[22]}]
set_property PACKAGE_PIN AF10 [get_ports {hdmi_data_o[21]}]
set_property PACKAGE_PIN AE10 [get_ports {hdmi_data_o[20]}]
set_property PACKAGE_PIN AE11 [get_ports {hdmi_data_o[19]}]
set_property PACKAGE_PIN AD11 [get_ports {hdmi_data_o[18]}]
set_property PACKAGE_PIN AC11 [get_ports {hdmi_data_o[17]}]
set_property PACKAGE_PIN AC12 [get_ports {hdmi_data_o[16]}]
set_property PACKAGE_PIN AD8 [get_ports {hdmi_data_o[15]}]
set_property PACKAGE_PIN AC8 [get_ports {hdmi_data_o[14]}]
set_property PACKAGE_PIN AB11 [get_ports {hdmi_data_o[13]}]
set_property PACKAGE_PIN AB12 [get_ports {hdmi_data_o[12]}]
set_property PACKAGE_PIN AC13 [get_ports {hdmi_data_o[11]}]
set_property PACKAGE_PIN AC14 [get_ports {hdmi_data_o[10]}]
set_property PACKAGE_PIN AD13 [get_ports {hdmi_data_o[9]}]
set_property PACKAGE_PIN AD14 [get_ports {hdmi_data_o[8]}]
set_property PACKAGE_PIN W8 [get_ports {hdmi_data_o[7]}]
set_property PACKAGE_PIN Y8 [get_ports {hdmi_data_o[6]}]
set_property PACKAGE_PIN W9 [get_ports {hdmi_data_o[5]}]
set_property PACKAGE_PIN AA8 [get_ports {hdmi_data_o[4]}]
set_property PACKAGE_PIN AA9 [get_ports {hdmi_data_o[3]}]
set_property PACKAGE_PIN AA10 [get_ports {hdmi_data_o[2]}]
set_property PACKAGE_PIN AB9 [get_ports {hdmi_data_o[1]}]
set_property PACKAGE_PIN AB10 [get_ports {hdmi_data_o[0]}]

# HDMI IO Standards
set_property IOSTANDARD LVTTL [get_ports hdmi_de_o]
set_property IOSTANDARD LVTTL [get_ports hdmi_hs_o]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_i2c_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_i2c_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_nrst_o]
set_property IOSTANDARD LVTTL [get_ports hdmi_pixel_clk_o]
set_property IOSTANDARD LVTTL [get_ports hdmi_vs_o]
set_property IOSTANDARD LVCMOS18 [get_ports video_src_sel]

set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[23]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[22]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[21]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[20]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[19]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[18]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[17]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[16]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[15]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[14]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[13]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[12]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[11]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[10]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[9]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[8]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[7]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[6]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[5]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[4]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[3]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[2]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[1]}]
set_property IOSTANDARD LVTTL [get_ports {hdmi_data_o[0]}]


# Drive Strength Settings
set_property DRIVE 16 [get_ports hdmi_de_o]
set_property DRIVE 16 [get_ports hdmi_hs_o]
set_property DRIVE 8 [get_ports hdmi_i2c_scl_io]
set_property DRIVE 8 [get_ports hdmi_i2c_sda_io]
set_property DRIVE 4 [get_ports hdmi_nrst_o]
set_property DRIVE 16 [get_ports hdmi_pixel_clk_o]
set_property DRIVE 16 [get_ports hdmi_vs_o]
set_property DRIVE 4 [get_ports phy_ready_o]

set_property DRIVE 16 [get_ports {hdmi_data_o[23]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[22]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[21]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[20]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[19]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[18]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[17]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[16]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[15]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[14]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[13]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[12]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[11]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[10]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[9]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[8]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[7]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[6]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[5]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[4]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[3]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[2]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[1]}]
set_property DRIVE 16 [get_ports {hdmi_data_o[0]}]

# Slew Rate Settings
set_property SLEW FAST [get_ports hdmi_de_o]
set_property SLEW FAST [get_ports hdmi_hs_o]
set_property SLEW SLOW [get_ports hdmi_nrst_o]
set_property SLEW FAST [get_ports hdmi_pixel_clk_o]
set_property SLEW FAST [get_ports hdmi_vs_o]
set_property SLEW SLOW [get_ports phy_ready_o]
set_property SLEW SLOW [get_ports hdmi_i2c_sda_io]
set_property SLEW SLOW [get_ports hdmi_i2c_scl_io]

set_property SLEW FAST [get_ports {hdmi_data_o[23]}]
set_property SLEW FAST [get_ports {hdmi_data_o[22]}]
set_property SLEW FAST [get_ports {hdmi_data_o[21]}]
set_property SLEW FAST [get_ports {hdmi_data_o[20]}]
set_property SLEW FAST [get_ports {hdmi_data_o[19]}]
set_property SLEW FAST [get_ports {hdmi_data_o[18]}]
set_property SLEW FAST [get_ports {hdmi_data_o[17]}]
set_property SLEW FAST [get_ports {hdmi_data_o[16]}]
set_property SLEW FAST [get_ports {hdmi_data_o[15]}]
set_property SLEW FAST [get_ports {hdmi_data_o[14]}]
set_property SLEW FAST [get_ports {hdmi_data_o[13]}]
set_property SLEW FAST [get_ports {hdmi_data_o[12]}]
set_property SLEW FAST [get_ports {hdmi_data_o[11]}]
set_property SLEW FAST [get_ports {hdmi_data_o[10]}]
set_property SLEW FAST [get_ports {hdmi_data_o[9]}]
set_property SLEW FAST [get_ports {hdmi_data_o[8]}]
set_property SLEW FAST [get_ports {hdmi_data_o[7]}]
set_property SLEW FAST [get_ports {hdmi_data_o[6]}]
set_property SLEW FAST [get_ports {hdmi_data_o[5]}]
set_property SLEW FAST [get_ports {hdmi_data_o[4]}]
set_property SLEW FAST [get_ports {hdmi_data_o[3]}]
set_property SLEW FAST [get_ports {hdmi_data_o[2]}]
set_property SLEW FAST [get_ports {hdmi_data_o[1]}]
set_property SLEW FAST [get_ports {hdmi_data_o[0]}]

# Termination Settings


set_input_delay 1.000 [get_ports {hdmi_i2c_scl_io hdmi_i2c_sda_io reset_i video_src_sel}]
set_output_delay 1.000 [get_ports {{hdmi_data_o[0]} {hdmi_data_o[1]} {hdmi_data_o[2]} {hdmi_data_o[3]} {hdmi_data_o[4]} {hdmi_data_o[5]} {hdmi_data_o[6]} {hdmi_data_o[7]} {hdmi_data_o[8]} {hdmi_data_o[9]} {hdmi_data_o[10]} {hdmi_data_o[11]} {hdmi_data_o[12]} {hdmi_data_o[13]} {hdmi_data_o[14]} {hdmi_data_o[15]} {hdmi_data_o[16]} {hdmi_data_o[17]} {hdmi_data_o[18]} {hdmi_data_o[19]} {hdmi_data_o[20]} {hdmi_data_o[21]} {hdmi_data_o[22]} {hdmi_data_o[23]} hdmi_de_o hdmi_hs_o hdmi_i2c_scl_io hdmi_i2c_sda_io hdmi_nrst_o hdmi_pixel_clk_o hdmi_vs_o mmcm_locked_o phy_ready_o}]









create_clock -period 2.500 -name {dphy_clk_i[1]} -waveform {0.000 1.250} -add [get_ports {dphy_clk_i[1]}]
create_clock -period 5.000 -name sys_clk_p_i -waveform {0.000 2.500} -add [get_ports sys_clk_p_i]
create_clock -period 10.000 -name byte_clk -waveform {0.000 5.000} -add [get_nets -hierarchical *dphy_byte_clk*]
#create_clock -period 3.367 -name pixel_clk -waveform {0.000 1.684} -add [get_nets -hierarchical *clk_297m*]
#create_clock -period 13.461 -name pixel_clk_div -waveform {0.000 6.731} -add [get_nets -hierarchical *mutli_pixel_clk_x*]


set_property OFFCHIP_TERM NONE [get_ports hdmi_de_o]
set_property OFFCHIP_TERM NONE [get_ports hdmi_hs_o]
set_property OFFCHIP_TERM NONE [get_ports hdmi_pixel_clk_o]
set_property OFFCHIP_TERM NONE [get_ports hdmi_vs_o]
set_property OFFCHIP_TERM NONE [get_ports mmcm_locked_o]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[23]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[22]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[21]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[20]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[19]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[18]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[17]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[16]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[15]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[14]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[13]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[12]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[11]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[10]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[9]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[8]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[7]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[6]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[5]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[4]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[3]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[2]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[1]]
set_property OFFCHIP_TERM NONE [get_ports hdmi_data_o[0]]

