set_property PACKAGE_PIN C14 [get_ports {STRER[0]}]
set_property PACKAGE_PIN D14 [get_ports {STRER[1]}]
set_property PACKAGE_PIN F14 [get_ports {STRER[2]}]
set_property PACKAGE_PIN G14 [get_ports {STRER[3]}]

set_property PACKAGE_PIN E15 [get_ports {DATA[0]}]
set_property PACKAGE_PIN D15 [get_ports {DATA[1]}]
set_property PACKAGE_PIN A15 [get_ports {DATA[2]}]
set_property PACKAGE_PIN B15 [get_ports {DATA[3]}]
set_property PACKAGE_PIN B14 [get_ports {DATA[4]}]
set_property PACKAGE_PIN A14 [get_ports {DATA[5]}]
set_property PACKAGE_PIN D13 [get_ports {DATA[6]}]
set_property PACKAGE_PIN C13 [get_ports {DATA[7]}]
set_property PACKAGE_PIN F13 [get_ports {DATA[8]}]
set_property PACKAGE_PIN C12 [get_ports {DATA[9]}]
set_property PACKAGE_PIN A12 [get_ports {DATA[10]}]
set_property PACKAGE_PIN B12 [get_ports {DATA[11]}]
set_property PACKAGE_PIN E8 [get_ports {DATA[12]}]
set_property PACKAGE_PIN D8 [get_ports {DATA[13]}]
set_property PACKAGE_PIN C8 [get_ports {DATA[14]}]
set_property PACKAGE_PIN D9 [get_ports {DATA[15]}]
set_property SLEW FAST [get_ports {BE[1]}]
set_property SLEW FAST [get_ports {BE[0]}]
set_property SLEW FAST [get_ports {DATA[15]}]
set_property SLEW FAST [get_ports {DATA[14]}]
set_property SLEW FAST [get_ports {DATA[13]}]
set_property SLEW FAST [get_ports {DATA[12]}]
set_property SLEW FAST [get_ports {DATA[11]}]
set_property SLEW FAST [get_ports {DATA[10]}]
set_property SLEW FAST [get_ports {DATA[9]}]
set_property SLEW FAST [get_ports {DATA[8]}]
set_property SLEW FAST [get_ports {DATA[7]}]
set_property SLEW FAST [get_ports {DATA[6]}]
set_property SLEW FAST [get_ports {DATA[5]}]
set_property SLEW FAST [get_ports {DATA[4]}]
set_property SLEW FAST [get_ports {DATA[3]}]
set_property SLEW FAST [get_ports {DATA[2]}]
set_property SLEW FAST [get_ports {DATA[1]}]
set_property SLEW FAST [get_ports {DATA[0]}]
set_property DRIVE 12 [get_ports {BE[1]}]
set_property DRIVE 12 [get_ports {BE[0]}]

set_property PACKAGE_PIN J13 [get_ports ERDIS]

create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports CLK]
set_input_jitter [get_clocks -regexp .*] 0.800
set_input_delay -clock [get_clocks -regexp .*] -rise -min 6.000 [get_ports -regexp -filter { NAME =~  ".*" && DIRECTION == "INOUT" }]
set_input_delay -clock [get_clocks -regexp .*] -rise -min 6.000 [get_ports RXF_N]
set_output_delay -clock [get_clocks -regexp .*] -min 9.000 [get_ports -regexp -filter { NAME =~  ".*" && DIRECTION == "INOUT" }]
set_output_delay -clock [get_clocks -regexp .*] -min 9.000 [get_ports {WR_N RD_N OE_N}]

set_property PACKAGE_PIN E11 [get_ports {BE[0]}]
set_property PACKAGE_PIN F12 [get_ports {BE[1]}]
set_property PACKAGE_PIN E13 [get_ports CLK]
set_property PACKAGE_PIN E22 [get_ports HRST_N]
set_property PACKAGE_PIN G12 [get_ports MLTCN]
set_property PACKAGE_PIN B10 [get_ports OE_N]
set_property PACKAGE_PIN H12 [get_ports R_OOB]
set_property PACKAGE_PIN A10 [get_ports RD_N]
set_property PACKAGE_PIN C11 [get_ports RXF_N]
set_property PACKAGE_PIN E10 [get_ports SRST_N]
set_property PACKAGE_PIN A13 [get_ports STREN]
set_property PACKAGE_PIN B11 [get_ports TXE_N]
set_property PACKAGE_PIN H13 [get_ports W_OOB]
set_property PACKAGE_PIN D11 [get_ports WR_N]

set_property IOSTANDARD LVCMOS18 [get_ports CLK]
set_property IOSTANDARD LVCMOS18 [get_ports {BE[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {BE[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {DATA[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {STRER[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {STRER[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {STRER[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {STRER[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports ERDIS]
set_property IOSTANDARD LVCMOS18 [get_ports HRST_N]
set_property IOSTANDARD LVCMOS18 [get_ports MLTCN]
set_property IOSTANDARD LVCMOS18 [get_ports OE_N]
set_property IOSTANDARD LVCMOS18 [get_ports R_OOB]
set_property IOSTANDARD LVCMOS18 [get_ports RD_N]
set_property IOSTANDARD LVCMOS18 [get_ports RXF_N]
set_property IOSTANDARD LVCMOS18 [get_ports SRST_N]
set_property IOSTANDARD LVCMOS18 [get_ports STREN]
set_property IOSTANDARD LVCMOS18 [get_ports TXE_N]
set_property IOSTANDARD LVCMOS18 [get_ports W_OOB]
set_property IOSTANDARD LVCMOS18 [get_ports WR_N]

set_property PACKAGE_PIN H11 [get_ports LED_TEST]
set_property IOSTANDARD LVCMOS18 [get_ports LED_TEST]

set_property DRIVE 12 [get_ports LED_TEST]
