create_clock -period 5.000 -name sys_clk_p -waveform {0.000 2.500} -add [get_ports sys_clk_p_i]

set_property PACKAGE_PIN AF15 [get_ports hdmi_i2c_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_i2c_scl_io]
set_property PACKAGE_PIN AE16 [get_ports hdmi_i2c_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_i2c_sda_io]
set_property PACKAGE_PIN AF12 [get_ports hdmi_out_nrst_o]
set_property IOSTANDARD LVTTL [get_ports hdmi_out_nrst_o]

set_property PACKAGE_PIN E22 [get_ports reset_i]
set_property IOSTANDARD LVCMOS18 [get_ports reset_i]

set_property PACKAGE_PIN G12 [get_ports rdy_i]
set_property IOSTANDARD LVCMOS18 [get_ports rdy_i]

set_property PACKAGE_PIN F8 [get_ports gpio_probe_o]
set_property IOSTANDARD LVCMOS18 [get_ports gpio_probe_o]

set_property IOSTANDARD LVDS [get_ports sys_clk_p_i]
set_property PACKAGE_PIN D19 [get_ports sys_clk_p_i]
set_property PACKAGE_PIN C19 [get_ports sys_clk_n_i]
set_property IOSTANDARD LVDS [get_ports sys_clk_n_i]

set_property PACKAGE_PIN AA15 [get_ports video_de_o]
set_property IOSTANDARD LVTTL [get_ports video_de_o]

set_property PACKAGE_PIN AB15 [get_ports video_hs_o]
set_property IOSTANDARD LVTTL [get_ports video_hs_o]

set_property PACKAGE_PIN W15 [get_ports video_pixel_clk_o]
set_property IOSTANDARD LVTTL [get_ports video_pixel_clk_o]

set_property PACKAGE_PIN Y15 [get_ports video_vs_o]
set_property IOSTANDARD LVTTL [get_ports video_vs_o]

set_property PACKAGE_PIN AA19 [get_ports {dphy_clk_i[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_clk_i[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_clk_i[0]}]
#set_property ODT RTT_NONE [get_ports {dphy_clk_i[1]}]
#set_property ODT RTT_NONE [get_ports {dphy_clk_i[0]}]

set_property PACKAGE_PIN W20 [get_ports {dphy_d0_i[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_d0_i[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_d0_i[0]}]

set_property PACKAGE_PIN AC19 [get_ports {dphy_d1_i[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_d1_i[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_d1_i[0]}]

set_property PACKAGE_PIN AD20 [get_ports {dphy_d2_i[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_d2_i[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_d2_i[0]}]

set_property PACKAGE_PIN AB21 [get_ports {dphy_d3_i[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_d3_i[1]}]
set_property IOSTANDARD MIPI_DPHY_DCI [get_ports {dphy_d3_i[0]}]

create_clock -period 2.500 -name csi -waveform {0.000 1.250} [get_ports {dphy_clk_i[1]}]
create_clock -period 2.500 -name csi2 -waveform {1.250 2.500} [get_ports {dphy_clk_i[0]}]
set_input_delay -clock [get_clocks csi] 1.000 [get_ports {{dphy_d0_i[0]} {dphy_d0_i[1]} {dphy_d1_i[0]} {dphy_d1_i[1]} {dphy_d2_i[0]} {dphy_d2_i[1]} {dphy_d3_i[0]} {dphy_d3_i[1]}}]
set_input_delay -clock [get_clocks csi] -clock_fall 1.000 [get_ports {{dphy_d0_i[0]} {dphy_d0_i[1]} {dphy_d1_i[0]} {dphy_d1_i[1]} {dphy_d2_i[0]} {dphy_d2_i[1]} {dphy_d3_i[0]} {dphy_d3_i[1]}}]

set_property PACKAGE_PIN AD9 [get_ports {video_data_o[23]}]
set_property PACKAGE_PIN AC9 [get_ports {video_data_o[22]}]
set_property PACKAGE_PIN AF10 [get_ports {video_data_o[21]}]
set_property PACKAGE_PIN AE10 [get_ports {video_data_o[20]}]
set_property PACKAGE_PIN AE11 [get_ports {video_data_o[19]}]
set_property PACKAGE_PIN AD11 [get_ports {video_data_o[18]}]
set_property PACKAGE_PIN AC11 [get_ports {video_data_o[17]}]
set_property PACKAGE_PIN AC12 [get_ports {video_data_o[16]}]
set_property PACKAGE_PIN AD8 [get_ports {video_data_o[15]}]
set_property PACKAGE_PIN AC8 [get_ports {video_data_o[14]}]
set_property PACKAGE_PIN AB11 [get_ports {video_data_o[13]}]
set_property PACKAGE_PIN AB12 [get_ports {video_data_o[12]}]
set_property PACKAGE_PIN AC13 [get_ports {video_data_o[11]}]
set_property PACKAGE_PIN AC14 [get_ports {video_data_o[10]}]
set_property PACKAGE_PIN AD13 [get_ports {video_data_o[9]}]
set_property PACKAGE_PIN AD14 [get_ports {video_data_o[8]}]
set_property PACKAGE_PIN W8 [get_ports {video_data_o[7]}]
set_property PACKAGE_PIN Y8 [get_ports {video_data_o[6]}]
set_property PACKAGE_PIN W9 [get_ports {video_data_o[5]}]
set_property PACKAGE_PIN AA8 [get_ports {video_data_o[4]}]
set_property PACKAGE_PIN AA9 [get_ports {video_data_o[3]}]
set_property PACKAGE_PIN AA10 [get_ports {video_data_o[2]}]
set_property PACKAGE_PIN AB9 [get_ports {video_data_o[1]}]
set_property PACKAGE_PIN AB10 [get_ports {video_data_o[0]}]

set_property IOSTANDARD LVTTL [get_ports {video_data_o[23]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[22]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[21]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[20]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[19]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[18]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[17]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[16]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[15]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[14]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[13]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[12]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[11]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[10]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[9]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[8]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[7]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[6]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[5]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[4]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[3]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[2]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[1]}]
set_property IOSTANDARD LVTTL [get_ports {video_data_o[0]}]


set_property PACKAGE_PIN G11 [get_ports locked_led_o]
set_property IOSTANDARD LVCMOS18 [get_ports locked_led_o]

set_property DRIVE 16 [get_ports {video_data_o[23]}]
set_property DRIVE 16 [get_ports {video_data_o[22]}]
set_property DRIVE 16 [get_ports {video_data_o[21]}]
set_property DRIVE 16 [get_ports {video_data_o[20]}]
set_property DRIVE 16 [get_ports {video_data_o[19]}]
set_property DRIVE 16 [get_ports {video_data_o[18]}]
set_property DRIVE 16 [get_ports {video_data_o[17]}]
set_property DRIVE 16 [get_ports {video_data_o[16]}]
set_property DRIVE 16 [get_ports {video_data_o[15]}]
set_property DRIVE 16 [get_ports {video_data_o[14]}]
set_property DRIVE 16 [get_ports {video_data_o[13]}]
set_property DRIVE 16 [get_ports {video_data_o[12]}]
set_property DRIVE 16 [get_ports {video_data_o[11]}]
set_property DRIVE 16 [get_ports {video_data_o[10]}]
set_property DRIVE 16 [get_ports {video_data_o[9]}]
set_property DRIVE 16 [get_ports {video_data_o[8]}]
set_property DRIVE 16 [get_ports {video_data_o[7]}]
set_property DRIVE 16 [get_ports {video_data_o[6]}]
set_property DRIVE 16 [get_ports {video_data_o[5]}]
set_property DRIVE 16 [get_ports {video_data_o[4]}]
set_property DRIVE 16 [get_ports {video_data_o[3]}]
set_property DRIVE 16 [get_ports {video_data_o[2]}]
set_property DRIVE 16 [get_ports {video_data_o[1]}]
set_property DRIVE 16 [get_ports {video_data_o[0]}]
set_property SLEW FAST [get_ports {video_data_o[23]}]
set_property SLEW FAST [get_ports {video_data_o[22]}]
set_property SLEW FAST [get_ports {video_data_o[21]}]
set_property SLEW FAST [get_ports {video_data_o[20]}]
set_property SLEW FAST [get_ports {video_data_o[19]}]
set_property SLEW FAST [get_ports {video_data_o[18]}]
set_property SLEW FAST [get_ports {video_data_o[17]}]
set_property SLEW FAST [get_ports {video_data_o[16]}]
set_property SLEW FAST [get_ports {video_data_o[15]}]
set_property SLEW FAST [get_ports {video_data_o[14]}]
set_property SLEW FAST [get_ports {video_data_o[13]}]
set_property SLEW FAST [get_ports {video_data_o[12]}]
set_property SLEW FAST [get_ports {video_data_o[11]}]
set_property SLEW FAST [get_ports {video_data_o[10]}]
set_property SLEW FAST [get_ports {video_data_o[9]}]
set_property SLEW FAST [get_ports {video_data_o[8]}]
set_property SLEW FAST [get_ports {video_data_o[7]}]
set_property SLEW FAST [get_ports {video_data_o[6]}]
set_property SLEW FAST [get_ports {video_data_o[5]}]
set_property SLEW FAST [get_ports {video_data_o[4]}]
set_property SLEW FAST [get_ports {video_data_o[3]}]
set_property SLEW FAST [get_ports {video_data_o[2]}]
set_property SLEW FAST [get_ports {video_data_o[1]}]
set_property SLEW FAST [get_ports {video_data_o[0]}]
set_property DRIVE 16 [get_ports video_de_o]
set_property SLEW FAST [get_ports video_de_o]
set_property DRIVE 16 [get_ports video_hs_o]
set_property SLEW FAST [get_ports video_hs_o]
set_property DRIVE 16 [get_ports video_pixel_clk_o]
set_property SLEW FAST [get_ports video_pixel_clk_o]
set_property DRIVE 16 [get_ports video_vs_o]
set_property SLEW FAST [get_ports video_vs_o]





set_property DIFF_TERM_ADV TERM_NONE [get_ports {dphy_clk_i[1]}]
set_property DIFF_TERM_ADV TERM_NONE [get_ports {dphy_clk_i[0]}]
set_property DIFF_TERM_ADV TERM_NONE [get_ports {dphy_d0_i[1]}]
set_property DIFF_TERM_ADV TERM_NONE [get_ports {dphy_d0_i[0]}]
set_property DIFF_TERM_ADV TERM_NONE [get_ports {dphy_d1_i[1]}]
set_property DIFF_TERM_ADV TERM_NONE [get_ports {dphy_d1_i[0]}]
set_property DIFF_TERM_ADV TERM_NONE [get_ports {dphy_d2_i[1]}]
set_property DIFF_TERM_ADV TERM_NONE [get_ports {dphy_d2_i[0]}]
set_property DIFF_TERM_ADV TERM_NONE [get_ports {dphy_d3_i[1]}]
set_property DIFF_TERM_ADV TERM_NONE [get_ports {dphy_d3_i[0]}]

set_property OFFCHIP_TERM NONE [get_ports gpio_probe_o]

set_property OFFCHIP_TERM NONE [get_ports hdmi_i2c_scl_io]
set_property OFFCHIP_TERM NONE [get_ports hdmi_i2c_sda_io]
set_property OFFCHIP_TERM NONE [get_ports hdmi_out_nrst_o]
set_property OFFCHIP_TERM NONE [get_ports locked_led_o]
set_property OFFCHIP_TERM NONE [get_ports rdy_o]
set_property OFFCHIP_TERM NONE [get_ports video_de_o]
set_property OFFCHIP_TERM NONE [get_ports video_hs_o]
set_property OFFCHIP_TERM NONE [get_ports video_pixel_clk_o]
set_property OFFCHIP_TERM NONE [get_ports video_vs_o]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[23]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[22]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[21]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[20]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[19]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[18]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[17]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[16]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[15]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[14]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[13]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[12]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[11]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[10]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[9]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[8]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[7]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[6]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[5]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[4]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[3]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[2]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[1]]
set_property OFFCHIP_TERM NONE [get_ports video_data_o[0]]
set_property PACKAGE_PIN G12 [get_ports rdy_o]
set_property IOSTANDARD LVCMOS18 [get_ports rdy_o]
